# KUC, PGR107, Lec9

# 1. operating data in pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1.1 ufunc

In [3]:

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))

print(ser)
# random numbers

0    6
1    3
2    7
3    4
dtype: int64

In [4]:
# (2)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
print(df)

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [5]:
print('perform exp....func on df:')
## uncomment the following
print(np.exp(df))

perform exp....func on df:
             A            B           C            D
0   403.428793  8103.083928    7.389056   403.428793
1  1096.633158    54.598150   20.085537  1096.633158
2  1096.633158     7.389056  148.413159    54.598150

In [6]:
print(np.exp(0))

1.0

In [7]:
# (3) * index alignment
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

print(A)
print(B)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64

In [8]:
print(A+B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [9]:
print(A.add(B))

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [10]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [11]:
# (4) index alignment with data frame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('ab'))
A

   a   b
0  1  11
1  5   1

In [12]:
A['a']

0    1
1    5
Name: a, dtype: int64

In [13]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('bac'))
B

   b  a  c
0  4  0  9
1  5  8  0
2  9  2  6

# A
# a b c
8,6, NAN
17,3, NAN
NAN, NAN, NAN


#B
# b a c
8,1,9
8,9,4
1,3,6

# B
# a b c
1, 8, 9
9, 8, 4
3, 1, 6

# A.add(B) ==
[8,6, NAN
17,3, NAN] +
[1, 8, 9
9, 8, 4
3, 1, 6]
= [9, 14, NAN
26, 11, NAN,
NAN, NAN, NAN]

In [14]:
print(A.add(B))

      a     b   c
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [15]:
A + B

      a     b   c
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [16]:
A.add(B,fill_value=0)
# see documentation here: https://pandas.pydata.org/pandas-docs/version/0.25/reference/api/pandas.Series.add.html

      a     b    c
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0